#!/usr/bin/env bash
# Bash script must accept 2 arguments: domain, subdomain:
# The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

info () {
#    data=$(dig "$2"."$1" | awk '/ANSWER SECTION:/ {getline; print}' | awk '{print $1, $4}')
    echo "$(dig "$2"."$1" | awk '/ANSWER SECTION:/{getline; print "The subdomain " $1 " is a " $4 " record and points to " $5}')"
}


if [ "$#" == 1 ]
then
  info "$1" "www"
  info "$1" "lb-01"
  info "$1" "web-01"
  info "$1" "web-02"
elif [ "$#" == 2 ]
then
  info "$1" "$2"
fi
