#!/usr/bin/env bash
#  a Bash script that transfers a file from our client to a server
# run with ./0-transfer_file another_page.html 35.168.7.107 ubuntu ~/.ssh/school

another_page.html

if [ "$#" -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
path="$1"
ip="$2"
username="$3"
path_to_ssh="$4"
scp -o StrictHostKeyChecking=no "$path" "$username@$ip":~
