#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Test the Nginx configuration
sudo nginx -t

# Restart Nginx
sudo service nginx restart