#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y install haproxy
sudo echo "frontend  shaza-frontend
        bind *:80
        mode http
        default_backend shaza-backend
backend shaza-backend
        balance roundrobin
        server web-01 35.168.7.107:80 check
        server web-02 100.25.140.120:80 check" | sudo tee /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
