#! /usr/bin/env bash
# a Bash script that generates a MySQL dump
# and creates a compressed archive out of it.

current_date=$(date +"%d-%m-%Y")
dump_file="backup.sql"
archive_file="$current_date.tar.gz"

mysqldump --all-databases > "$dump_file"
tar -czvf backup.sql backup.sql

