#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

# fix enabled-sites to have listen :80 not 8080

# Define the new port you want to set
new_port=80

# Use sed to replace the old port with the new port in the configuration file
sudo sed -i "s/listen 8080 default_server;/listen $new_port default_server;/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:$new_port default_server ipv6only=on;/g" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
