#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a list format

for file in * ; do
	if [ -f "$file" ]
		then
			case $file in
			*-*) cut -d "-" -f 2 <<< "$file";;

			esac
	fi

done
