#!/usr/bin/env bash
# Configure web-01 so that its firewall redirects port 8080/TCP to port 80/TCP.

sudo apt-get update
sudo apt-get -y install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw route allow proto tcp from any to any port 8080 redirect to 80
sudo ufw reload

