#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts_copy

echo "127.0.0.2		localhost" > hosts_copy
echo "8.8.8.8		facebook.com" >> hosts_copy  # >> to append and avoid overwrite

cp ~/hosts_copy /etc/hosts